// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfo87l2jY-m9ZG1rIkK-7qNUYWKlbFv18',
    appId: '1:490473358247:web:c580c29b4b9ad219c62c82',
    messagingSenderId: '490473358247',
    projectId: 'sustomer-app',
    authDomain: 'sustomer-app.firebaseapp.com',
    storageBucket: 'sustomer-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEdCb2zdKU1475yTZZ2d-76-0CxLWWIQs',
    appId: '1:490473358247:android:bf750bcca7552580c62c82',
    messagingSenderId: '490473358247',
    projectId: 'sustomer-app',
    storageBucket: 'sustomer-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnxY9hH3gCKwTdXXP_QzmbZxpFqZy_PWI',
    appId: '1:490473358247:ios:e10c9ff8f9fa690dc62c82',
    messagingSenderId: '490473358247',
    projectId: 'sustomer-app',
    storageBucket: 'sustomer-app.appspot.com',
    iosClientId: '490473358247-68v25n5s8okfrnj7abj6cfqqvcr61kvr.apps.googleusercontent.com',
    iosBundleId: 'com.example.sustomerTask',
  );
}
